name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform-validate.yml
    with:
      terraform-version: "1.9.8"
      roots: |
        terraform/modules/docker-app